# Generated by Django 3.1.1 on 2020-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201022_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
